
## LIBRARIES 

library(bigmemory)
library(NMF)
library(rtracklayer)
library(tidyverse)
library(Seurat)
library(SeuratObject)
library(DESeq2)
library(Matrix)
library(DoubletFinder)
library(ggplot2)
library(ggridges)
library(dplyr)
library(scDblFinder)
library(fgsea)
library(msigdbr)
library(biomaRt)
library(harmony)
library(data.table)
library(ggh4x)
library(patchwork)
library(BayesPrism)
library(qsmooth)
library(umap)
library(ggfortify)
library(viridis)
library(qsmooth)
library(msigdbdf)
library(MASS)
library(limma)
library(corrplot)
library(ggpmisc)
library(ggpubr)
install.packages("ggpubr")
